### ISSUE TITLE
[Q] Chat Template

### ISSUE THREAD

**Issue by NightMachinery** [Gryphe/BlockMerge_Gradient#2]
The model card says:

> Prompt Format
> This model primarily uses Alpaca formatting, so for optimal model performance, use:

```
<System prompt/Character Card>

### Instruction:
Your instruction or question here.
For roleplay purposes, I suggest the following - Write <CHAR NAME>'s next reply in a chat between <YOUR NAME> and <CHAR NAME>. Write a single reply only.

### Response:
```

Can you an example of how to format the following? 
```
System: This is a story taking place in a faraway forest with many dark creatures that come out under the moonlight.

Narrator: Once upon a time, a man transmigrated into a squirrel in a strange forest.

Man: "What has happened to me?"

Strange Whisper: "Find the source ... Drink from the source ..."

Man: "What the hell?"
```

Is the instruction-finetuning dataset available somewhere? I want to see what template the model was finetuned on exactly.

**Comment by jsgv** [comment]
Could you share the jinja template that should be used? @Gryphe 

I ended up using https://github.com/vllm-project/vllm/blob/ee378f3d49f1404a72ec0948f0a2553f7c3a3726/examples/template_alpaca.jinja
